// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_habit = "CgkInuiR96cbEAIQFA"; // <GPGSID>
        public const string leaderboard_ranking = "CgkInuiR96cbEAIQAQ"; // <GPGSID>
        public const string achievement_expert = "CgkInuiR96cbEAIQCg"; // <GPGSID>
        public const string achievement_fortune = "CgkInuiR96cbEAIQDg"; // <GPGSID>
        public const string achievement_saver = "CgkInuiR96cbEAIQDw"; // <GPGSID>
        public const string achievement_pro = "CgkInuiR96cbEAIQCQ"; // <GPGSID>
        public const string achievement_beginner = "CgkInuiR96cbEAIQEw"; // <GPGSID>
        public const string achievement_greed = "CgkInuiR96cbEAIQBQ"; // <GPGSID>
        public const string achievement_rich = "CgkInuiR96cbEAIQEQ"; // <GPGSID>
        public const string achievement_newbie = "CgkInuiR96cbEAIQBw"; // <GPGSID>
        public const string achievement_developer = "CgkInuiR96cbEAIQDA"; // <GPGSID>
        public const string achievement_small = "CgkInuiR96cbEAIQDQ"; // <GPGSID>
        public const string achievement_collector = "CgkInuiR96cbEAIQEA"; // <GPGSID>
        public const string achievement_master = "CgkInuiR96cbEAIQCw"; // <GPGSID>
        public const string achievement_addict = "CgkInuiR96cbEAIQFQ"; // <GPGSID>
        public const string achievement_persist = "CgkInuiR96cbEAIQBg"; // <GPGSID>
        public const string achievement_fat = "CgkInuiR96cbEAIQEg"; // <GPGSID>
        public const string achievement_normal = "CgkInuiR96cbEAIQCA"; // <GPGSID>

}

